# Day2: Pandas 탐색적 자료 분석


## 학습 내용
1. DataFrame 이해
2. 분석목적에 적합한 데이터 전처리

In [ ]:
import os
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

data_dir = # "데이터 파일 위치한 경로"

## 1. CSV / Excel 자료 읽기

- **csv 자료 읽기**
- `pd.read_csv()`: CSV (Comma Separated Values) 파일 읽기. 쉼표나 다른 구분자로 항목이 나뉜 텍스트 데이터
    - `header` : 컬럼(열) 이름으로 사용할 행의 번호 (0부터 시작), header=None
    - `index_col` : 행의 이름(인덱스)으로 사용할 컬럼의 번호, index_col=0
    - `sep`: 데이터 항목을 구분하는 구분자 (str 자료형). 기본값은 쉼표(,)
    - `skiprows`: 파일의 맨 위부터 지정한 개수만큼의 행을 건너뛰고 읽음, skiprows=3 (처음 3줄 건너뛰기)
    - `nrows`: 파일에서 읽어올 행의 개수. 대용량 파일에서 일부만 테스트로 불러올 때 유용, nrows=1000 (처음 1000줄만 읽기)
    - 이외에는 매뉴얼 참조

In [ ]:
## csv 전체
titanic_path = os.path.join(data_dir, "titanic.csv") # os. 을 사용하면 사용하는 운영체제에 맞춰 경로 처리를 수행합니다.
titanic = pd.read_csv(titanic_path)
# pd.read_csv(경로, header = 행 번호, index_col = 인덱스 컬럼 번호, sep = "항목 구분자", skiprows = 위에서 건너뛸 행의 수, nrows = 파일에서 읽어들일 행의 개수)
display("titanic = ", titanic.head())

'titanic = '

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

- **excel 자료 읽기**
- `pd.read_excel()`: Excel (.xlsx, .xls) 파일 읽기
  - `header` : 컬럼(열) 이름으로 사용할 행의 번호 (0부터 시작), header=None
  - `index_col` : 행의 이름(인덱스)으로 사용할 컬럼의 번호, index_col=0
  - `skiprows`: 파일의 맨 위부터 지정한 개수만큼의 행을 건너뛰고 읽음, skiprows=3 (처음 3줄 건너뛰기)
  - `nrows`: 파일에서 읽어올 행의 개수. 대용량 파일에서 일부만 테스트로 불러올 때 유용, nrows=1000 (처음 1000줄만 읽기)

- `mtcars` 자료
    - 1974년 자동차 트렌드에서 발췌한 32가지 차종의 연비, 마력, 무게 등 다양한 사양 정보를 포함
    - 상관 분석, 회귀 분석 등 다양한 통계 기법을 적용하는 예시 자료로 활용

In [ ]:
mtcars_path = os.path.join(data_dir, "mtcars.xlsx")
mtcars = pd.read_excel(mtcars_path, header= 0, index_col= None)
# pd.read_excel(경로, header = 행 번호, index_col = 인덱스 컬럼 번호, skiprows = 위에서 건너뛸 행의 수, nrows = 파일에서 읽어들일 행의 개수)
display("mtcars = ", mtcars.head())

'mtcars = '

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4.0,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4.0,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,NaN,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3.0,1
4,Hornet Sportabout,18.7,8,NaN,175,3.15,3.440,17.02,0,0,3.0,2

- ### <csv 자료 읽기 문제>
    - 아래와 같은 결과가 나오도록 지정된 경로에 있는 csv 파일을 읽어 보시오
    - `csv_filepath = "../data/cars.csv"`

In [ ]:
'''
csv_filepath = "../data/cars.csv"
print(cars)
출력결과:

    speed	dist
1	4	2
2	4	10
3	7	4
4	7	22
5	8	16
6	9	10
7	10	18
8	10	26
9	10	34
10	11	17
'''

csv_filepath =  os.path.join(data_dir, "cars.csv")
cars = pd.read_csv(csv_filepath, skiprows = 3, index_col = 0)

print(cars.head(10))

- ### <excel 자료 읽기 문제>
    - 아래와 같은 결과가 나오도록 지정된 경로에 있는 excel 파일을 읽어 보시오
    - `excel_filepath = "../data/stock price.xlsx"`

In [4]:
'''
excel_filepath = "../data/stock price.xlsx"
print(stock)
출력결과:

                id          value   price
stock_name                               
한미약품        128940   59385.666667  421000
CJ E&M      130960   58540.666667   98900
엔에스쇼핑       138250   14558.666667   13200
이마트         139480  239230.833333  254500
녹십자엠에스      142280     468.833333   10200
삼양사         145990   82750.000000   82000
종근당         185750   40293.666667  100500
쿠쿠홀딩스       192400  179204.666667  177500
툴젠          199800   -2514.333333  115400
모두투어리츠      204210    3093.333333    3475
'''

excel_filepath = os.path.join(data_dir, "stock price.xlsx")
stock = pd.read_excel(excel_filepath, index_col="stock_name")

print(stock)

                id          value   price
stock_name
한미약품        128940   59385.666667  421000
CJ E&M      130960   58540.666667   98900
엔에스쇼핑       138250   14558.666667   13200
이마트         139480  239230.833333  254500
녹십자엠에스      142280     468.833333   10200
삼양사         145990   82750.000000   82000
종근당         185750   40293.666667  100500
쿠쿠홀딩스       192400  179204.666667  177500
툴젠          199800   -2514.333333  115400
모두투어리츠      204210    3093.333333    3475

## 2. DataFrame 다루기

- **데이터 탐색및 확인**
    - `df.head()`: $\text{DataFrame}$의 상위 $\text{5}$개 행을 반환, df.head(10)(상위 $\text{10}$개 행 반환)
    - `df.tail()`: $\text{DataFrame}$의 하위 $\text{5}$개 행을 반환, df.tail(3)
    - `df.shape`: $\text{DataFrame}$의 크기를 (행의 수, 열의 수) 튜플로 반환
    - `df.columns`: $\text{DataFrame}$의 변수명을 반환
    - `df.info()`: $\text{DataFrame}$에 대한 `전반적인 정보`를 요약해서 출력
    - `df.describe()`: 숫자형 컬럼들의 기술 통계를 요약 (개수, 평균, 표준편차, 최솟값, 최댓값, 사분위수 등)
    - `df.astype()`: 컬럼의 `자료형 (dtype)`을 변경, df['Pclass'].astype('category')
    - `df.tolist()`: DataFrame 자료를 list 자료로 변경
    - `df.dropna()`: `NaN` 값을 제거

In [5]:
titanic = pd.read_csv(titanic_path)
print("titanic type = ", type(titanic))

titanic type =  <class 'pandas.core.frame.DataFrame'>

In [ ]:
print(type(titanic))
display(titanic.head(10))

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [7]:
display(titanic.tail())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [8]:
rows, cols = titanic.shape
print("titanic 총 행 = ", rows)
print("titanic 총 열 = ", cols)

titanic 총 행 =  891
titanic 총 열 =  12

In [9]:
col_names = titanic.columns
display("titanic.columns = ", col_names)

'titanic.columns = '

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

## 연속형 데이터
- 비율 척도 ex) 키, 몸무게, 거리
- 구간 척도 ex) 온도, 기온  
(차이점은 숫자의 절대적인 의미를 가지는지 차이)

## 범주형 데이터
- 명목형 ex) 남/여, 생존/사망
- 순서형  
(분석 시에는 데이터 타입을 별도로 변환해서 사용하는 것을 추천)  
(astype 이용해 명목형은 category 로, 순서형은 )

In [ ]:
display(titanic.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

None

In [11]:
## 데이터 타입 변경 전
display(titanic.describe())

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
## 데이터 타입 변경 

titanic["passengerId"] = titanic["passengerId"].astype("object")
titanic["survived"] = titanic["survived"].astype("category")
titanic["pclass"] = titanic["pclass"].astype("category")

display(titanic.info())
# titanic.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    category
 1   Survived     891 non-null    category
 2   Pclass       891 non-null    category
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: category(3), float64(2), int64(2), object(5)
memory usage: 105.8+ KB

None

- ### <데이터 타입 수정하기 문제>
    - mtcars데이터를 읽고 mtcars.describe()를 수행하고자 할 때 출력결과가 아래와 같도록 데이터의 타입을 적절하게 수정하시오

        - [1]	mpg:	float	연비 (Miles per Gallon, 마일당 갤런). 자동차의 연료 효율성.
        - [2]	cyl:	int	실린더 개수 (Number of cylinders). 엔진의 실린더 수.
        - [3]	disp:	float	배기량 (Displacement in cu.in.), 엔진의 크기.
        - [4]	hp:	    int	마력 (Gross horsepower). 엔진의 힘.
        - [5]	drat:	float	후륜 액슬 비율 (Rear axle ratio). 차량의 기어비 관련 수치.
        - [6]	wt: 	float	차량 무게 (Weight, 1000 lbs 단위).
        - [7]	qsec:	float	1/4 마일 도달 시간 (1/4 mile time). 차량의 가속 능력을 나타내는 지표.
        - [8]	vs: 	int	엔진 형태 (Engine Type). $\text{0}$은 $\text{V}$형 엔진, $\text{1}$은 직선형 엔진 ($\text{straight}$ engine)을 의미합니다.
        - [9]	am: 	int	변속기 종류 (Transmission). $\text{0}$은 자동 변속기 ($\text{automatic}$), $\text{1}$은 수동 변속기 ($\text{manual}$)를 의미합니다.
        - [10]gear:	int	전진 기어 개수 (Number of forward gears).
        - [11]carb:	int	카뷰레터 개수 (Number of carburetors).

In [ ]:
##
# mtcars.describe()

# [츨력 결과]
'''
        mpg	        cyl	        disp	    hp	        drat	    wt	        qsec	    gear	    carb
count	32.000000	32.000000	32.000000	32.000000	32.000000	32.000000	32.000000	32.000000	32.0000
mean	20.090625	6.187500	230.721875	146.687500	3.596563	3.217250	17.848750	3.687500	2.8125
std	6.026948	1.785922	123.938694	68.562868	0.534679	0.978457	1.786943	0.737804	1.6152
min	10.400000	4.000000	71.100000	52.000000	2.760000	1.513000	14.500000	3.000000	1.0000
25%	15.425000	4.000000	120.825000	96.500000	3.080000	2.581250	16.892500	3.000000	2.0000
50%	19.200000	6.000000	196.300000	123.000000	3.695000	3.325000	17.710000	4.000000	2.0000
75%	22.800000	8.000000	326.000000	180.000000	3.920000	3.610000	18.900000	4.000000	4.0000
max	33.900000	8.000000	472.000000	335.000000	4.930000	5.424000	22.900000	5.000000	8.0000
'''
mtcars_path = os.path.join(data_dir, "mtcars.xlsx")
mtcars = pd.read_excel(mtcars_path)

mtcars["vs"] = mtcars["vs"].astype('category') # astype 이용해 int64 에서 category 로 데이터 타입 변경
mtcars["am"] = mtcars["am"].astype('category') # astype 이용해 int64 에서 category 로 데이터 타입 변경


mtcars.describe()

- **DataFrame 데이터 접근 및 선택**
    - `df["column"]`: 특정 컬럼(Series 형태)을 선택, df['Age']
    - `df[["column1", "column2"]]`: 여러 개의 컬럼(DataFrame 형태)을 선택, df[['Name', 'Fare']]  
    (1개 이상의 컬럼을 선택할 경우 List 로 묶어서 사용)
    - `df.loc[]`: 레이블 (행 인덱스 이름, 컬럼 이름)을 사용하여 행과 열을 선택, df.loc[0, 'Name'] (0번 인덱스의 Name 값)
    - `df.iloc[]`: 정수 위치 (행 인덱스 번호, 열 인덱스 번호) 를 사용하여 행과 열을 선택

In [ ]:
# PassengerId 선택
passengers = titanic["passengerId"]
display("passengers = ", passengers)

'passengers = '

0        1
1        2
2        3
3        4
4        5
      ...
886    887
887    888
888    889
889    890
890    891
Name: PassengerId, Length: 891, dtype: category
Categories (891, int64): [1, 2, 3, 4, ..., 888, 889, 890, 891]

In [ ]:
titanic_sub = titanic[['survived', 'pclass', 'sex', 'age', 'fare']]
print(titanic_sub.head(10))

In [ ]:
# PassengerId, Survived 선택
passengers_survived = titanic[["passengerId", "survived"]]
display('titanic[["passengerId", "survived"]] = ', passengers_survived)
titanic.head()

'titanic[["PassengerId", "Survived"]] = '

    PassengerId Survived
0             1        0
1             2        1
2             3        1
3             4        1
4             5        0
..          ...      ...
886         887        0
887         888        1
888         889        0
889         890        1
890         891        0

[891 rows x 2 columns]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# PassengerId, Survived, Age 선택
passengers_survived_age = titanic[["passengerId", "survived", "age"]]
display('titanic[["passengerId", "survived", "age"]] = ', passengers_survived_age)

'titanic[["PassengerId", "Survived", "Age"]] = '

    PassengerId Survived   Age
0             1        0  22.0
1             2        1  38.0
2             3        1  26.0
3             4        1  35.0
4             5        0  35.0
..          ...      ...   ...
886         887        0  27.0
887         888        1  19.0
888         889        0   NaN
889         890        1  26.0
890         891        0  32.0

[891 rows x 3 columns]

## 인덱싱
- **loc 인덱싱**
    - 마지막행 포함해 출력
- **iloc 인덱싱**
    - 마지막행을 포함하지 않고 출력  

(직접 슬라이싱해도 되지만, loc나 iloc 를 사용하면 행과 열을 한번에 추출할 수 있기때문에 추천)

In [ ]:
# loc 선택
titanic_loc1 = titanic.loc[0, "survived"]
print('titanic.loc[0, "survived"] = ', titanic_loc1)

titanic.loc[0, "Survived"] =  0

In [ ]:
#loc 인덱싱
titanic_sub.loc[:10, ['survived', 'age']] # 이 경우 10번째 행 포함해 출력
titanic_sub.loc[3:5, ['survived', 'age']]

titanic_loc2 = titanic.loc[0:10, ["survived", "age", "pclass"]]
display('titanic.loc[0:10, ["survived", "age", "pclass"]] = ', titanic_loc2)

'titanic.loc[0:10, ["Survived", "Age", "Pclass"]] = '

   Survived   Age Pclass
0         0  22.0      3
1         1  38.0      1
2         1  26.0      3
3         1  35.0      1
4         0  35.0      3
5         0   NaN      3
6         0  54.0      1
7         0   2.0      3
8         1  27.0      3
9         1  14.0      2
10        1   4.0      3

In [ ]:
titanic_loc3 = titanic.loc[:, "survived":"parch"]
display('titanic.loc[:, "survived":"parch"] = ', titanic_loc3)

'titanic.loc[:, "Survived":"Parch"] = '

,Survived,Pclass,Name,Sex,Age,SibSp,Parch
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0
...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0

In [ ]:
# iloc를 이용한 선택
titanic_sub.iloc[3:6, ['survived', 'age']] # 6번째 행 제외하고 출력
titanic_sub.iloc[3:6, [0, 3]] # 6번째 행과 3번째열 제외하고 출력


titanic_iloc1 = titanic.iloc[:10, :3]
display("titanic_1.iloc[:10, :3] = ", titanic_iloc1)

'titanic_1.iloc[:10, :3] = '

  PassengerId Survived Pclass
0           1        0      3
1           2        1      1
2           3        1      3
3           4        1      1
4           5        0      3
5           6        0      3
6           7        0      1
7           8        0      3
8           9        1      3
9          10        1      2

In [20]:
titanic_iloc2 = titanic.iloc[10:20, [1, 2, 4, 5, 6, 7]]
display("titanic.iloc[10:20, [1, 2, 4, 5, 6, 7]] = ", titanic_iloc2)

'titanic.iloc[10:20, [1, 2, 4, 5, 6, 7]] = '

   Survived Pclass     Sex   Age  SibSp  Parch
10        1      3  female   4.0      1      1
11        1      1  female  58.0      0      0
12        0      3    male  20.0      0      0
13        0      3    male  39.0      1      5
14        0      3  female  14.0      0      0
15        1      2  female  55.0      0      0
16        0      3    male   2.0      4      1
17        1      2    male   NaN      0      0
18        0      3  female  31.0      1      0
19        1      3  female   NaN      0      0

- ### <DataFrame 자료 접근 문제>
    - DataFrame loc 인덱싱을 이용하여 아래의 출력 결과가 나오도록 데이터를 읽어 보시오

In [21]:
'''
print(titanic_loc_ex)

    Survived    Sex	Age	Pclass
0	0	male	22.0	3
1	1	female	38.0	1
2	1	female	26.0	3
3	1	female	35.0	1
4	0	male	35.0	3
5	0	male	NaN	    3
6	0	male	54.0	1
7	0	male	2.0	    3
8	1	female	27.0	3
9	1	female	14.0	2
10	1	female	4.0	    3   
'''

titanic_loc_ex = titanic.loc[0:10, ["Survived", "Sex", "Age", "Pclass"]]
print(titanic_loc_ex)

   Survived     Sex   Age Pclass
0         0    male  22.0      3
1         1  female  38.0      1
2         1  female  26.0      3
3         1  female  35.0      1
4         0    male  35.0      3
5         0    male   NaN      3
6         0    male  54.0      1
7         0    male   2.0      3
8         1  female  27.0      3
9         1  female  14.0      2
10        1  female   4.0      3

- DataFrame iloc 인덱싱을 이용하여 아래의 출력 결과가 나오도록 데이터를 읽어 보시오

In [22]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [23]:
'''
print(titanic_iloc_ex)

PassengerId	Survived	Pclass	Name
10	11	1	3	Sandstrom, Miss. Marguerite Rut
11	12	1	1	Bonnell, Miss. Elizabeth
12	13	0	3	Saundercock, Mr. William Henry
13	14	0	3	Andersson, Mr. Anders Johan
14	15	0	3	Vestrom, Miss. Hulda Amanda Adolfina
15	16	1	2	Hewlett, Mrs. (Mary D Kingcome)
16	17	0	3	Rice, Master. Eugene
17	18	1	2	Williams, Mr. Charles Eugene
18	19	0	3	Vander Planke, Mrs. Julius (Emelia Maria Vande...
19	20	1	3	Masselmani, Mrs. Fatima
20	21	0	2	Fynney, Mr. Joseph

'''

titanic_iloc_ex = titanic.iloc[10:21, :4]
display(titanic_iloc_ex)

,PassengerId,Survived,Pclass,Name
10,11,1,3,"Sandstrom, Miss. Marguerite Rut"
11,12,1,1,"Bonnell, Miss. Elizabeth"
12,13,0,3,"Saundercock, Mr. William Henry"
13,14,0,3,"Andersson, Mr. Anders Johan"
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina"
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)"
16,17,0,3,"Rice, Master. Eugene"
17,18,1,2,"Williams, Mr. Charles Eugene"
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande..."
19,20,1,3,"Masselmani, Mrs. Fatima"
20,21,0,2,"Fynney, Mr. Joseph J"

## 3. 데이터 기초 통계량

- **중심의 위치측도**
    - `표본평균 (Sample Mean)`
        - 중심을 나타내는 측도 중에서 가장 많이 사용되는 방법
        - 자료의 무게 중심을 나타냄
        - $\overline x = \frac{\sum_{i = 1}^{n} x_i}{n}$
        - 자료의 이상치 (Outlier)에 영향을 많이 받음 (Trimmed mean)
    
    - `중앙값 (Median)`
        - 전체 관측값을 크기 순으로 나열한 했을 때 중앙에 위치한 값
        - 자료의 갯수(n) 이 홀수이면 $\frac{n+1}{2}$ 번째 관측값
        - 자료의 갯수(n) 이 짝수이면 $\frac{n}{2}$과 $\frac{n+1}{2}$ 번째 관측값의 평균값
        - 자료의 이상치 (Outlier)에 영향을 적게 받음

- **DataFrame 메소드**
    - `.mean()`: DataFrame/Series 의 평균, titanic["Fare"].mean()
    - `.median()`: DataFrame/Series 의 중앙값, titanic["Fare"].median()

In [24]:
fare_mean = titanic["Fare"].mean()
print("fare_mean = ", fare_mean)

fare_mean =  32.204207968574636

In [25]:
fare_median = titanic["Fare"].median()
print("fare_median = ", fare_median)

fare_median =  14.4542

- **분산과 표준편차**
    - 자료가 중심으로 부터  얼마나 퍼져있는 지를 표현 수치
    - $S^2 = \frac{\sum_i^N (X_{i}-\overline{X})^2}{N}$  
  <br />
    - sd = $\sqrt{S^2} = S$
    - 범위(Range): 최댓값 - 최솟값

In [26]:
## For 구문을 이용한 titanic 요금 분산

titanic_fare = titanic["Fare"]
# print("titanic_fare = ", titanic_fare)

fare_sum = 0
for i in titanic_fare:
    fare_sum = fare_sum + i

fare_mean = fare_sum/891

fare_var = 0

for i in titanic_fare:
    fare_var = fare_var + (i - fare_mean)**2

fare_var = fare_var/891

print("Variance of fare = ", fare_var)

Variance of fare =  2466.6653116850434

In [27]:
## For 구문을 이용한 titanic 요금 표준편차

fare_std = np.sqrt(fare_var)
print("std of fare = ", fare_std)

std of fare =  49.66553444477411

In [28]:
## titanic 요금 분위 범위
fare_range = titanic_fare.max() - titanic_fare.min()
print("range of fare = ", fare_range)

range of fare =  512.3292

In [29]:
## DataFrame method를 이용한 분산, 표준편차, 범위

titanic_fare = titanic["Fare"]

titanic_fare_var = titanic_fare.var()
titanic_fare_std = titanic_fare.std()

print("titanic_fare.var() = ", titanic_fare_var)
print("titanic_fare.std() = ", titanic_fare_std)

titanic_fare.var() =  2469.436845743116
titanic_fare.std() =  49.6934285971809

* 결과 DataFrame으로 정리하기

In [30]:
summary_stat = {
    "mean": fare_mean,
    "median": fare_median,
    "variance": fare_var,
    "std": fare_std,
    "range": fare_range
}

display(summary_stat)

{'mean': 32.2042079685746,
 'median': np.float64(14.4542),
 'variance': 2466.6653116850434,
 'std': np.float64(49.66553444477411),
 'range': np.float64(512.3292)}

In [32]:
df_summary = pd.DataFrame([summary_stat], index=['Fare'])
display("titanic 요금 통계량 = ", df_summary.round(3))

'titanic 요금 통계량 = '

        mean  median  variance     std    range
Fare  32.204  14.454  2466.665  49.666  512.329

## 4. 데이터 정제 및 전처리
- **메서드란**: 파이썬의 함수작동 형식, 클래스내에 정의된 함수
- **정제 및 전처리 메서드**:
  - `.isnull()`: $\text{DataFrame}$의 각 요소가 **결측치**($\text{NaN}$)인지 여부를 불리언 $\text{DataFrame}$으로 반환
  - `.dropna()`: 결측치가 있는 행 또는 열을 제거
  - `.fillna()`: 결측치를 특정 값으로 채움
  - `.drop()`: 행 또는 열을 제거
  - `.rename()`: 인덱스 또는 열 이름을 변경
  - `.value_counts()`: 특정 열의 고유값별 개수 (빈도)를 반환
  - `.unique()`: 특정 열의 고유값 목록을 배열로 반환

In [2]:
titanic_path = os.path.join(data_dir, "titanic.csv")
titanic = pd.read_csv(titanic_path, index_col="PassengerId")
titanic.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### 결측치 확인 (.isnull() / isna())

In [ ]:
# 각 열별 결측치 개수 확인
print("\n--- .isnull()을 이용한 결측치 확인 ---")
print(titanic.isnull().head(10))
print(titanic.isna().head(10))

--- .isnull()을 이용한 결측치 확인 ---
             Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
PassengerId
1               False   False  False  False  False  False  False   False
2               False   False  False  False  False  False  False   False
3               False   False  False  False  False  False  False   False
4               False   False  False  False  False  False  False   False
5               False   False  False  False  False  False  False   False
6               False   False  False  False   True  False  False   False
7               False   False  False  False  False  False  False   False
8               False   False  False  False  False  False  False   False
9               False   False  False  False  False  False  False   False
10              False   False  False  False  False  False  False   False

              Fare  Cabin  Embarked
PassengerId
1            False   True     False
2            False  False     False
3            False   True     False
4            False  False     False
5            False   True     False
6            False   True     False
7            False  False     False
8            False   True     False
9            False   True     False
10           False   True     False

In [ ]:
print("\n--- .isnull().sum(axis = 0)을 이용한 결측치 확인 ---")
print(titanic.isnull().sum(axis = 0))

#titanic.drop_duplicates()

--- .isnull().sum(axis = 0)을 이용한 결측치 확인 ---
Survived      0
Pclass        0
Name          0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       687
Embarked      2
dtype: int64

### 결측치 채우기 (.fillna())

In [ ]:
# Age 열의 NaN 값을 0으로 채움
titanic_fill0 = titanic['age'].fillna(0)
print(titanic_fill0.head(10))

PassengerId
1     22.0
2     38.0
3     26.0
4     35.0
5     35.0
6      0.0
7     54.0
8      2.0
9     27.0
10    14.0
Name: Age, dtype: float64

In [ ]:
# Age의 평균 계산
mean_age = titanic['age'].mean()

# Age 열의 NaN 값을 평균값으로 채움
titanic['age'] = titanic['age'].fillna(mean_age)

print("\n--- .fillna()로 Age 결측치 채우기 ---")
print(titanic[['age']].head(7)) # 값이 채워졌는지 확인

--- .fillna()로 Age 결측치 채우기 ---
              Age
PassengerId
1            22.0
2            38.0
3            26.0
4            35.0
5            35.0
6             0.0
7            54.0

### 결측치 제거 (.dropna())

In [ ]:
# Cabin 열에 NaN이 있는 행 제거 (원본을 건드리지 않기 위해 새로운 변수에 저장)
titanic_dropped_cabin = titanic.dropna(subset=['cabin'])

print("\n--- dropna()로 Cabin 결측 행 제거 후 크기 확인 ---")
print(f"원본 데이터 행 수: {len(titanic)}")
print(f"Cabin 결측치 제거 후 행 수: {len(titanic_dropped_cabin)}")

--- dropna()로 Cabin 결측 행 제거 후 크기 확인 ---
원본 데이터 행 수: 891
Cabin 결측치 제거 후 행 수: 204

In [23]:
# Titanic에서 NaN이 있는 모든 행 제거 (원본을 건드리지 않기 위해 새로운 변수에 저장)
titanic_dropped = titanic.dropna()

print("\n--- dropna()로 Cabin 결측 행 제거 후 크기 확인 ---")
print(f"원본 데이터 행 수: {len(titanic)}")
print(f"Cabin 결측치 제거 후 행 수: {len(titanic_dropped)}")
display(titanic_dropped.head(10))

--- dropna()로 Cabin 결측 행 제거 후 크기 확인 ---
원본 데이터 행 수: 891
Cabin 결측치 제거 후 행 수: 183

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C

### 불필요한 열 제거 (.drop())

In [ ]:
# PassengerId 열과 Name 열 제거 (axis=1은 열을 의미하며, 원본 titanic 수정)
titanic_selected = titanic.drop(columns=[ 'name', "ticket", "cabin", "embarked"])

print("\n--- .drop()으로 불필요한 열 제거 ---")
print(titanic_selected.head(20))

--- .drop()으로 불필요한 열 제거 ---
             Survived  Pclass     Sex   Age  SibSp  Parch     Fare
PassengerId
1                   0       3    male  22.0      1      0   7.2500
2                   1       1  female  38.0      1      0  71.2833
3                   1       3  female  26.0      0      0   7.9250
4                   1       1  female  35.0      1      0  53.1000
5                   0       3    male  35.0      0      0   8.0500
6                   0       3    male   NaN      0      0   8.4583
7                   0       1    male  54.0      0      0  51.8625
8                   0       3    male   2.0      3      1  21.0750
9                   1       3  female  27.0      0      2  11.1333
10                  1       2  female  14.0      1      0  30.0708
11                  1       3  female   4.0      1      1  16.7000
12                  1       1  female  58.0      0      0  26.5500
13                  0       3    male  20.0      0      0   8.0500
14                  0       3    male  39.0      1      5  31.2750
15                  0       3  female  14.0      0      0   7.8542
16                  1       2  female  55.0      0      0  16.0000
17                  0       3    male   2.0      4      1  29.1250
18                  1       2    male   NaN      0      0  13.0000
19                  0       3  female  31.0      1      0  18.0000
20                  1       3  female   NaN      0      0   7.2250

### <불필요한 열 제거 문제>
- `titanic_selected` 자료에서 **SibSp, Parch** 열을 제거하고 자료를  `titanic_selected_v2`로 저장하고 프린트 하시오

In [ ]:
# < 풀이 >

titanic_selected_v2 = titanic_selected.drop(columns={"sibSp", "parch"})
print("titanic_selected_v2 \n", titanic_selected_v2)

titanic_selected_v2
              Survived  Pclass     Sex   Age     Fare
PassengerId
1                   0       3    male  22.0   7.2500
2                   1       1  female  38.0  71.2833
3                   1       3  female  26.0   7.9250
4                   1       1  female  35.0  53.1000
5                   0       3    male  35.0   8.0500
...               ...     ...     ...   ...      ...
887                 0       2    male  27.0  13.0000
888                 1       1  female  19.0  30.0000
889                 0       3  female   NaN  23.4500
890                 1       1    male  26.0  30.0000
891                 0       3    male  32.0   7.7500

[891 rows x 5 columns]

### 열 이름 변경 (.rename())

In [ ]:
# columns 딕셔너리를 사용하여 열 이름 변경
titanic_renamed = titanic_selected.rename(
    columns={'survived': '생존여부'})

print("\n---.rename()으로 열 이름 변경 ---")
print(titanic_renamed.head())

---.rename()으로 열 이름 변경 ---
             생존여부  Pclass     Sex   Age  SibSp  Parch     Fare
PassengerId
1               0       3    male  22.0      1      0   7.2500
2               1       1  female  38.0      1      0  71.2833
3               1       3  female  26.0      0      0   7.9250
4               1       1  female  35.0      1      0  53.1000
5               0       3    male  35.0      0      0   8.0500

### <변수명 바꾸기 문제>
- `titanic_selected` 자료를 이용하여 **'Survived' -> '생존여부', 'Pclass' -> '객실등급', 'Sex' -> '성별', 'Age' -> '나이',  'SibSp' -> '가족친지수',  'Parch' -> '부모',  'Fare' -> '요금' **로 변경하여 titanic_renamed로 저장하시오

In [ ]:
# <풀이>

titanic_renamed = titanic_selected.rename(
    columns={'survived': '생존여부',
             'pclass': '객실등급',
             'sex': '성별',
             'age': '나이',
             'sibSp': '가족친지수',
             'parch': '부모',
             'fare': '요금'}
    )

print(titanic_renamed.head())

### 고유값 목록 확인 (.unique())

In [ ]:
# Sex 열의 고유값 확인
sex_unique = titanic['sex'].unique()

print("\n--- unique()로 Sex 고유값 확인 ---")
print(sex_unique)

--- unique()로 Sex 고유값 확인 ---
['male' 'female']

In [ ]:
# Embarked 열의 고유값 확인
Embarked_unique = titanic['embarked'].unique()
# titanic['embarked'].unique()

print("\n--- unique()로 Embarked 고유값 확인 ---")
print(Embarked_unique)

--- unique()로 Embarked 고유값 확인 ---
['S' 'C' 'Q' nan]

### <고유값 목록 확인 문제>
- `titanic` 자료에서 **Cabin** 에 대한 고유값 목록을 확인하고 프린트 하시오

In [ ]:
# < 풀이 >

titanic_unique = titanic["cabin"].unique()
print(titanic_unique)

[nan 'C85' 'C123' 'E46' 'G6' 'C103' 'D56' 'A6' 'C23 C25 C27' 'B78' 'D33'
 'B30' 'C52' 'B28' 'C83' 'F33' 'F G73' 'E31' 'A5' 'D10 D12' 'D26' 'C110'
 'B58 B60' 'E101' 'F E69' 'D47' 'B86' 'F2' 'C2' 'E33' 'B19' 'A7' 'C49'
 'F4' 'A32' 'B4' 'B80' 'A31' 'D36' 'D15' 'C93' 'C78' 'D35' 'C87' 'B77'
 'E67' 'B94' 'C125' 'C99' 'C118' 'D7' 'A19' 'B49' 'D' 'C22 C26' 'C106'
 'C65' 'E36' 'C54' 'B57 B59 B63 B66' 'C7' 'E34' 'C32' 'B18' 'C124' 'C91'
 'E40' 'T' 'C128' 'D37' 'B35' 'E50' 'C82' 'B96 B98' 'E10' 'E44' 'A34'
 'C104' 'C111' 'C92' 'E38' 'D21' 'E12' 'E63' 'A14' 'B37' 'C30' 'D20' 'B79'
 'E25' 'D46' 'B73' 'C95' 'B38' 'B39' 'B22' 'C86' 'C70' 'A16' 'C101' 'C68'
 'A10' 'E68' 'B41' 'A20' 'D19' 'D50' 'D9' 'A23' 'B50' 'A26' 'D48' 'E58'
 'C126' 'B71' 'B51 B53 B55' 'D49' 'B5' 'B20' 'F G63' 'C62 C64' 'E24' 'C90'
 'C45' 'E8' 'B101' 'D45' 'C46' 'D30' 'E121' 'D11' 'E77' 'F38' 'B3' 'D6'
 'B82 B84' 'D17' 'A36' 'B102' 'B69' 'E49' 'C47' 'D28' 'E17' 'A24' 'C50'
 'B42' 'C148']

### 고유값별 빈도 확인 (.value_counts())

In [ ]:
# TicketClass 열의 고유값별 개수 확인
class_counts = titanic['pclass'].value_counts()
# titanic_rename['생존유무'].value_counts()

print("\n---.value_counts()로 TicketClass 빈도 확인 ---")
print(class_counts) # 정렬은 별도 작업 필요

---.value_counts()로 TicketClass 빈도 확인 ---
Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [ ]:
embarked_counts = titanic['embarked'].value_counts(dropna=False)
print("\n---.value_counts()로 TicketClass 빈도 확인 ---")
print(embarked_counts)

---.value_counts()로 TicketClass 빈도 확인 ---
Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

### <고유값별 빈도확인 문제>
- `titanic` 자료에서  생존자와 사망자의 빈도수를 확인하고 프린트해 보시오

In [ ]:
# < 풀이 >

survived_count = titanic["survived"].value_counts()
print(survived_count)

Survived
0    549
1    342
Name: count, dtype: int64

## 5. 데이터 조작 및 계산
- 데이터를 변형하거나 통계적 계산을 수행하는 데 사용
- **조작 및 계산 메서드**:
  - `.sort_values()`: 하나 이상의 열을 기준으로 정렬
  - `.sort_indexs()`: 하나 이상의 인덱스를 기준으로 정렬
  - `.replace()`: DataFrame 또는 $\text{Series}$의 특정 값을 다른 값으로 변경
  - `.groupby()`: 특정 열을 기준으로 데이터를 그룹화

- **< mtcars >** 자료 소개 
- mtcars는 통계 소프트웨어 R에 내장된 데이터셋으로, 데이터 분석을 위한 예제 자료로 널리 사용됩니다. 이 데이터셋은 1974년 미국 잡지 '모터 트렌드 US(Motor Trend US)'에 실린 내용을 기반으로 하며, 1973~1974년식 자동차 32대에 대한 연료 소비량 및 10가지 자동차 디자인 및 성능 측면의 정보를 포함하고 있습니다. 
- mtcars 데이터셋은 32개의 관측치(자동차 모델)와 11개의 변수로 구성되어 있습니다. 각 변수는 다음과 같은 정보를 담고 있습니다.

    - `mpg`: 마일/갤런(연비). 1갤런당 주행할 수 있는 마일 수
    - `cyl`: 실린더 수
    - `disp`: 배기량 (입방인치)
    - `hp`: 총 마력
    - `drat`: 후륜 차축 비율
    - `wt`: 중량 (1000파운드)
    - `qsec`: 1/4마일 도달 시간 (가속도 측정)
    - `vs`: 엔진 유형 (0 = V-형, 1 = 직렬형)
    - `am`: 변속기 유형 (0 = 자동, 1 = 수동)
    - `gear`: 전진 기어 수
    - `carb`: 기화기 수

In [17]:
mtcars_path = os.path.join(data_dir, "mtcars.xlsx")
mtcars = pd.read_excel(mtcars_path, index_col=0)
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4.0,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4.0,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,NaN,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3.0,1
Hornet Sportabout,18.7,8,NaN,175,3.15,3.440,17.02,0,0,3.0,2

### 열 값 기준으로 정렬 (.sort_values())

In [ ]:
# mpg (연비) 기준으로 내림차순 정렬 (ascending=False)
sorted_by_mpg = mtcars.sort_values(by='mpg', ascending=False) # by='컬럼명'
# sorted_by_mpg = mtcars.sort_values("mpg", ascending=False)

print("\n--- .sort_values() (mpg 내림차순 정렬) ---")
print(sorted_by_mpg.head())

--- .sort_values() (mpg 내림차순 정렬) ---
                 mpg  cyl  disp   hp  drat     wt   qsec  vs  am  gear  carb
Toyota Corolla  33.9    4  71.1   65  4.22  1.835  19.90   1   1   4.0     1
Fiat 128        32.4    4  78.7   66  4.08  2.200  19.47   1   1   4.0     1
Lotus Europa    30.4    4  95.1  113  3.77  1.513  16.90   1   1   NaN     2
Honda Civic     30.4    4  75.7   52  4.93  1.615  18.52   1   1   4.0     2
Fiat X1-9       27.3    4  79.0   66  4.08  1.935  18.90   1   1   4.0     1

In [112]:
# cyl, mpg (연비) 기준으로 내림차순 정렬 (ascending=False)
sorted_by_mpg = mtcars.sort_values(by=['cyl','mpg'], ascending=False)

print("\n--- .sort_values() (['cyl','mpg'] 내림차순 정렬) ---")
print(sorted_by_mpg.head())

--- .sort_values() (['cyl','mpg'] 내림차순 정렬) ---
                    mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
Pontiac Firebird   19.2    8  400.0  175  3.08  3.845  17.05   0   0     3
Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3
Merc 450SL         17.3    8  275.8  180  3.07  3.730  17.60   0   0     3
Merc 450SE         16.4    8  275.8  180  3.07  4.070  17.40   0   0     3
Ford Pantera L     15.8    8  351.0  264  4.22  3.170  14.50   0   1     5

                   carb
Pontiac Firebird      2
Hornet Sportabout     2
Merc 450SL            3
Merc 450SE            3
Ford Pantera L        4

### 인덱스 기준으로 정렬 (.sort_index())

In [117]:
# 인덱스 (차량 이름) 기준으로 오름차순 정렬 (기본값: ascending=True)
sorted_by_index = mtcars.sort_index()

print("\n--- .sort_index() (차량 이름 오름차순 정렬) ---")
print(sorted_by_index.head(10))

--- .sort_index() (차량 이름 오름차순 정렬) ---
                     mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
AMC Javelin         15.2    8  304.0  150  3.15  3.435  17.30   0   0     3
Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3
Camaro Z28          13.3    8  350.0  245  3.73  3.840  15.41   0   0     3
Chrysler Imperial   14.7    8  440.0  230  3.23  5.345  17.42   0   0     3
Datsun 710          22.8    4  108.0   93  3.85  2.320  18.61   1   1     4
Dodge Challenger    15.5    8  318.0  150  2.76  3.520  16.87   0   0     3
Duster 360          14.3    8  360.0  245  3.21  3.570  15.84   0   0     3
Ferrari Dino        19.7    6  145.0  175  3.62  2.770  15.50   0   1     5
Fiat 128            32.4    4   78.7   66  4.08  2.200  19.47   1   1     4
Fiat X1-9           27.3    4   79.0   66  4.08  1.935  18.90   1   1     4

                    carb
AMC Javelin            2
Cadillac Fleetwood     4
Camaro Z28             4
Chrysler Imperial      4
Datsun 710             1
Dodge Challenger       2
Duster 360             4
Ferrari Dino           6
Fiat 128               1
Fiat X1-9              1

### <열값 정렬 문제>
- `mtcars` 자료를 무게 (wt)에 따라서 오름차순으로 정리하고 자료를 mtcars_wt로 저장한 후 10 ~ 20 열에 있는 자료만 프린트 하시오

In [26]:
# < 풀이 >

mtcars_wt = mtcars.sort_values("wt", ascending=True)
mtcars_wt.head()

                 mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Lotus Europa    30.4    4   95.1  113  3.77  1.513  16.90   1   1   NaN     2
Honda Civic     30.4    4   75.7   52  4.93  1.615  18.52   1   1   4.0     2
Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   4.0     1
Fiat X1-9       27.3    4   79.0   66  4.08  1.935  18.90   1   1   4.0     1
Porsche 914-2   26.0    4  120.3   91  4.43  2.140  16.70   0   1   5.0     2

### 값 대체 (.replace())

In [119]:
# gear 열의 숫자 값을 문자열로 대체
# 3 -> 'Low Gear', 4 -> 'Mid Gear', 5 -> 'High Gear', 6 -> 'Sport Gear'
mtcars['gear_label'] = mtcars['gear'].replace({
    3: 'Low Gear',
    4: 'Mid Gear',
    5: 'High Gear',
    6: 'Sport Gear'
})

print("\n--- .replace() (gear 값 대체) ---")
print(mtcars[['gear', 'gear_label']].head(7))

--- .replace() (gear 값 대체) ---
                   gear gear_label
Mazda RX4             4   Mid Gear
Mazda RX4 Wag         4   Mid Gear
Datsun 710            4   Mid Gear
Hornet 4 Drive        3   Low Gear
Hornet Sportabout     3   Low Gear
Valiant               3   Low Gear
Duster 360            3   Low Gear

### <값 대체 문제>
- `mtcars` 자료에서 **am** 열의 값을 `0 -> 수동, 1 -> 자동` 으로 변경하고 프린트 하시오

In [27]:
# < 풀이 >

mtcars["am_rename"]= mtcars["am"].replace({0:"자동", 1:"수동"})
print(mtcars.head())

                    mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
Mazda RX4          21.0    6  160.0  110  3.90  2.620  16.46   0   1   4.0
Mazda RX4 Wag      21.0    6  160.0  110  3.90  2.875  17.02   0   1   4.0
Datsun 710         22.8    4  108.0   93  3.85  2.320  18.61   1   1   NaN
Hornet 4 Drive     21.4    6  258.0  110  3.08  3.215  19.44   1   0   3.0
Hornet Sportabout  18.7    8    NaN  175  3.15  3.440  17.02   0   0   3.0

                   carb am_rename
Mazda RX4             4        수동
Mazda RX4 Wag         4        수동
Datsun 710            1        수동
Hornet 4 Drive        1        자동
Hornet Sportabout     2        자동

### 데이터 그룹화 및 집계 (.groupby())

In [ ]:
# 'cyl' (실린더 개수) 기준으로 그룹화하고 'mpg'의 평균 계산
grouped_mpg = mtcars.groupby('cyl')['mpg'].mean()

print("\n--- .groupby() (실린더별 평균 mpg) ---")
print(grouped_mpg)
#grouped_mpg

--- 3. .groupby() (실린더별 평균 mpg) ---
cyl
4    26.663636
6    19.742857
8    15.100000
Name: mpg, dtype: float64

In [123]:
# 'cyl' (실린더 개수) 기준으로 그룹화하고 'mpg'의 중앙값 계산
grouped_mpg = mtcars.groupby('cyl')['mpg'].median()

print("\n--- .groupby() (실린더별 중앙값 mpg) ---")
print(grouped_mpg)

--- .groupby() (실린더별 중앙값 mpg) ---
cyl
4    26.0
6    19.7
8    15.2
Name: mpg, dtype: float64

In [124]:
# 'cyl' (실린더 개수) 기준으로 그룹화하고 'mpg'의 표준편차를 계산
grouped_mpg = mtcars.groupby('cyl')['mpg'].std()

print("\n--- .groupby() (실린더별 표준편차 mpg) ---")
print(grouped_mpg)

--- .groupby() (실린더별 표준편차 mpg) ---
cyl
4    4.509828
6    1.453567
8    2.560048
Name: mpg, dtype: float64

In [127]:
# 'am', 'cyl' (실린더 개수) 기준으로 그룹화하고 'mpg'의 평균 계산
grouped_mpg = mtcars.groupby(['am', 'cyl'])['mpg'].mean()

print("\n--- .groupby() (실린더별 평균 mpg) ---")
print(grouped_mpg)

--- .groupby() (실린더별 평균 mpg) ---
am  cyl
0   4      22.900000
    6      19.125000
    8      15.050000
1   4      28.075000
    6      20.566667
    8      15.400000
Name: mpg, dtype: float64

## 데이터 그룹화 및 집계 (언패킹 연산자 / 구조분해 할당)
- 언패킹 연산자(*) 와 구조분해 할당 이용

In [ ]:
# 언패킹 연산자
grouped_mpg = mtcars.groupby('cyl')
print(*grouped_mpg)

# 구조분해 할당
cyl_4, cyl_6, cyl_8 = grouped_mpg
print(cyl_4, cyl_6, cyl_8, sep="/n")

### <데이터 그룹화 및 집계 문제>
- `mtcars` 자료에서 **엔진유형 (vs)** 에 따른 **연비 (mpg)** 의 평균값과 표준편차를 각 각 구하고 프린트 하시오

In [32]:
# < 풀이 >
print("mean by am = ")
print(mtcars.groupby("am")["mpg"].mean())

print("\n std by am = ")
print(mtcars.groupby("am")["mpg"].std())

mean by am =
am
0    17.147368
1    24.392308
Name: mpg, dtype: float64

 std by am =
am
0    3.833966
1    6.166504
Name: mpg, dtype: float64

## 6. 데이터 인덱싱
- **인덱싱할 열의 값은 고유한 것이 좋습니다.**
- **데이터 인덱싱 메서드**:
  - `.reset_index()`: 현재 인덱스를 열로 변환하고, 새로운 기본 정수 인덱스를 설정
  - `.set_index()`: $\text{DataFrame}$의 특정 열을 새로운 인덱스로 설정
  - `.rank()`: 데이터의 순위를 매김

### 인덱스를 열로 변환 (.reset_index())

In [ ]:
# 현재 인덱스(차량 이름)를 'CarName'이라는 열로 변환
mtcars_reset = mtcars.reset_index(names=['CarName'], drop = False)

print("\n--- .reset_index() 적용 결과 ---")
print(mtcars_reset.head())

--- .reset_index() 적용 결과 ---
             CarName   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   4.0
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   4.0
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   NaN
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   3.0
4  Hornet Sportabout  18.7    8    NaN  175  3.15  3.440  17.02   0   0   3.0

   carb am_rename
0     4        수동
1     4        수동
2     1        수동
3     1        자동
4     2        자동

### 특정 열을 인덱스로 설정 (.set_index())

In [34]:
# 'CarName' 열을 제거하고 'cyl' 열을 새로운 인덱스로 설정
mtcars_set = mtcars_reset.set_index('cyl')

print("\n--- set_index() 적용 결과 (cyl 기준) ---")
print(mtcars_set)
print(f"\n새로운 인덱스 이름: {mtcars_set.index.name}")

--- set_index() 적용 결과 (cyl 기준) ---
                 CarName   mpg   disp   hp  drat     wt   qsec  vs  am  gear  \
cyl
6              Mazda RX4  21.0  160.0  110  3.90  2.620  16.46   0   1   4.0
6          Mazda RX4 Wag  21.0  160.0  110  3.90  2.875  17.02   0   1   4.0
4             Datsun 710  22.8  108.0   93  3.85  2.320  18.61   1   1   NaN
6         Hornet 4 Drive  21.4  258.0  110  3.08  3.215  19.44   1   0   3.0
8      Hornet Sportabout  18.7    NaN  175  3.15  3.440  17.02   0   0   3.0
6                Valiant  18.1  225.0  105  2.76  3.460  20.22   1   0   3.0
8             Duster 360  14.3  360.0  245  3.21  3.570  15.84   0   0   3.0
4              Merc 240D  24.4  146.7   62  3.69  3.190  20.00   1   0   4.0
4               Merc 230  22.8  140.8   95  3.92  3.150  22.90   1   0   4.0
6               Merc 280  19.2  167.6  123  3.92  3.440  18.30   1   0   4.0
6              Merc 280C  17.8  167.6  123  3.92  3.440  18.90   1   0   4.0
8             Merc 450SE  16.4  275.8  180  3.07  4.070  17.40   0   0   NaN
8             Merc 450SL  17.3  275.8  180  3.07  3.730  17.60   0   0   3.0
8            Merc 450SLC  15.2  275.8  180  3.07  3.780  18.00   0   0   3.0
8     Cadillac Fleetwood  10.4  472.0  205  2.93  5.250  17.98   0   0   3.0
8    Lincoln Continental  10.4  460.0  215  3.00  5.424  17.82   0   0   3.0
8      Chrysler Imperial  14.7    NaN  230  3.23  5.345  17.42   0   0   3.0
4               Fiat 128  32.4   78.7   66  4.08  2.200  19.47   1   1   4.0
4            Honda Civic  30.4   75.7   52  4.93  1.615  18.52   1   1   4.0
4         Toyota Corolla  33.9   71.1   65  4.22  1.835  19.90   1   1   4.0
4          Toyota Corona  21.5  120.1   97  3.70  2.465  20.01   1   0   NaN
8       Dodge Challenger  15.5    NaN  150  2.76  3.520  16.87   0   0   3.0
8            AMC Javelin  15.2  304.0  150  3.15  3.435  17.30   0   0   NaN
8             Camaro Z28  13.3  350.0  245  3.73  3.840  15.41   0   0   3.0
8       Pontiac Firebird  19.2  400.0  175  3.08  3.845  17.05   0   0   3.0
4              Fiat X1-9  27.3   79.0   66  4.08  1.935  18.90   1   1   4.0
4          Porsche 914-2  26.0  120.3   91  4.43  2.140  16.70   0   1   5.0
4           Lotus Europa  30.4   95.1  113  3.77  1.513  16.90   1   1   NaN
8         Ford Pantera L  15.8  351.0  264  4.22  3.170  14.50   0   1   NaN
6           Ferrari Dino  19.7  145.0  175  3.62  2.770  15.50   0   1   5.0
8          Maserati Bora  15.0    NaN  335  3.54  3.570  14.60   0   1   5.0
4             Volvo 142E  21.4  121.0  109  4.11  2.780  18.60   1   1   4.0

     carb am_rename
cyl
6       4        수동
6       4        수동
4       1        수동
6       1        자동
8       2        자동
6       1        자동
8       4        자동
4       2        자동
4       2        자동
6       4        자동
6       4        자동
8       3        자동
8       3        자동
8       3        자동
8       4        자동
8       4        자동
8       4        자동
4       1        수동
4       2        수동
4       1        수동
4       1        자동
8       2        자동
8       2        자동
8       4        자동
8       2        자동
4       1        수동
4       2        수동
4       2        수동
8       4        수동
6       6        수동
8       8        수동
4       2        수동

새로운 인덱스 이름: cyl

### <인덱스 바꾸기 문제>
- 위 예제에서 구해던 `mtcars_set`을 이용하여 0 부터 시작하는 정수형 인덱스로 바꾸고 기존의 인덱스 cyl을 컬럼으로 복귀시키고 자료를 `mtcars_reset`으로 저장하고 출력해 보시오

In [38]:
# < 풀이 >

mtcars_reset = mtcars_set.reset_index("cyl")
display(mtcars_reset.head())

,cyl,CarName,mpg,disp,hp,drat,wt,qsec,vs,am,gear,carb,am_rename
0,6,Mazda RX4,21.0,160.0,110,3.90,2.620,16.46,0,1,4.0,4,수동
1,6,Mazda RX4 Wag,21.0,160.0,110,3.90,2.875,17.02,0,1,4.0,4,수동
2,4,Datsun 710,22.8,108.0,93,3.85,2.320,18.61,1,1,NaN,1,수동
3,6,Hornet 4 Drive,21.4,258.0,110,3.08,3.215,19.44,1,0,3.0,1,자동
4,8,Hornet Sportabout,18.7,NaN,175,3.15,3.440,17.02,0,0,3.0,2,자동

### 데이터 순위 매기기 (.rank())

In [142]:
# hp가 낮은 순서대로 순위를 매김 (오름차순). 동점은 평균 순위를 부여.
# 62hp가 가장 낮으므로 1위
mtcars['hp_rank_asc'] = mtcars['hp'].rank(ascending=True, method='average')

print("\n--- 3.1. .rank() (hp 오름차순 순위) ---")
print(mtcars[['hp', 'hp_rank_asc']].sort_values('hp', ascending=False).head())

--- 3.1. .rank() (hp 오름차순 순위) ---
                    hp  hp_rank_asc
Maserati Bora      335         32.0
Ford Pantera L     264         31.0
Duster 360         245         29.5
Camaro Z28         245         29.5
Chrysler Imperial  230         28.0

In [145]:
# hp가 높은 순서대로 순위를 매김 (내림차순). 동점은 낮은 순위(min)를 부여.
# 245hp가 가장 높으므로 1위
mtcars['hp_rank_desc'] = mtcars['hp'].rank(ascending=False, method='min')

print("\n--- .rank() (hp 내림차순 순위, method='min') ---")
print(mtcars[['hp', 'hp_rank_desc']].sort_values('hp', ascending=False).head())

--- .rank() (hp 내림차순 순위, method='min') ---
                    hp  hp_rank_desc
Maserati Bora      335           1.0
Ford Pantera L     264           2.0
Duster 360         245           3.0
Camaro Z28         245           3.0
Chrysler Imperial  230           5.0

### <데이터 순위 매기기 문제>
- `mtcars` 자료를 이용하여 **연비 (mpg)** 에 따라서 가장 높은 값이 1 갖도록 만들고 순위자료를 `mtcars` 에 **ranked** 라는 열이름으로 저장하고 출력해 보시오

In [44]:
# < 풀이 >
mtcars["ranked"] = mtcars["mpg"].rank(ascending=False)
display(mtcars)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb,am_rename,ranked
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4.0,4,수동,13.5
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4.0,4,수동,13.5
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,NaN,1,수동,8.5
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3.0,1,자동,11.5
Hornet Sportabout,18.7,8,NaN,175,3.15,3.440,17.02,0,0,3.0,2,자동,18.0
Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3.0,1,자동,19.0
Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3.0,4,자동,29.0
Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4.0,2,자동,7.0
Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4.0,2,자동,8.5
Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4.0,4,자동,16.5
Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4.0,4,자동,20.0
Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,NaN,3,자동,22.0
Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3.0,3,자동,21.0
Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3.0,3,자동,25.5
Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3.0,4,자동,31.5
Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3.0,4,자동,31.5
Chrysler Imperial,14.7,8,NaN,230,3.23,5.345,17.42,0,0,3.0,4,자동,28.0
Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4.0,1,수동,2.0
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4.0,2,수동,3.5
Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4.0,1,수동,1.0
Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,NaN,1,자동,10.0
Dodge Challenger,15.5,8,NaN,150,2.76,3.520,16.87,0,0,3.0,2,자동,24.0
AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,NaN,2,자동,25.5
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3.0,4,자동,30.0
Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3.0,2,자동,16.5
Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4.0,1,수동,5.0
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5.0,2,수동,6.0
Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,NaN,2,수동,3.5
Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,NaN,4,수동,23.0
Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5.0,6,수동,15.0
Maserati Bora,15.0,8,NaN,335,3.54,3.570,14.60,0,1,5.0,8,수동,27.0
Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4.0,2,수동,11.5